name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
          unzip gradle-8.2-bin.zip
          chmod +x ./gradle-8.2/bin/gradle
          ./gradle-8.2/bin/gradle assembleDebug --stacktrace

      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OTC-AI-BOT-APK
          path: "**/*.apk"

          
